In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame({'text':['people watch Netflix','Netflix watch Netflix','people write comment','Netflix write comment'],'output':[1,1,0,0]})

In [3]:
df

text  output
0   people watch Netflix       1
1  Netflix watch Netflix       1
2   people write comment       0
3  Netflix write comment       0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [6]:
bow=cv.fit_transform(df['text'])

In [7]:
#vocab
print(cv.vocabulary_) #allotaed with the index no.

{'people': 2, 'watch': 3, 'netflix': 1, 'write': 4, 'comment': 0}


In [8]:
print(bow[0].toarray()) #sent 1
print(bow[1].toarray()) #sent 2
#comment netflix people watch write   --> arranged acc to the index no. and below array shows the no. of occurance of these words
# 0        1      1       1    0      --> for sent 1  

[[0 1 1 1 0]]
[[0 2 0 1 0]]


In [10]:
#if we bring new sent in df
cv.transform(['Netflix watch and write comment of Netflix']).toarray()

array([[1, 2, 0, 1, 1]], dtype=int64)

In [ ]:
#main moto is that if the word exist or not so if we put binary=True then the ans will be in just 0,1 form and would no show the no. of occurance of those words in doc
# go through sklearn.feature_extraction.text.CountVectorization page for further functions